[key_value_store.default]
type = "azure_cosmos"
key = "UmVhbGx5LCB5b3UgdGhvdWdodCBJIHByZXNlbnQgbXkgYWN0dWFsIGtleSBoZXJlPz8gQ29tZSBvbiEgOkQK"
account = "cosmos-spin"
database = "cosmos-sql-spin"
container = "kv"
